Update hatchling version support
Older versions of hatchling error out:

```
TypeError: Field `project.license-files` must be a table
```

since https://github.com/jupyter/jupyter_core/commit/2a2807b08381c6a1c84f1624889ccced03f8d93f